[package]
name = "dining_philosophers"
version = "0.1.0"
authors = ["Brian Harris <brianh@nvidia.com>"]

[dependencies]
rand = "0.4"
gfx = "0.16"
gfx_window_glutin = "0.19"
glutin = "0.11"
imgui = "0.0.18"
imgui-gfx-renderer = "0.0.18"
enum_primitive = "*"